const DIRECT_CLIENT = "NPSPCLIENTCCCCCCCCCCCCCCCCCCCCCCCCCC";
const LOCATION_PROGRAMS = "AVAILPRGRMCCCCCCCCCCCCCCCCCCCCCCCCCC";
const LOCATION_CODE = "ccb5b9f5-9432-485b-973b-6cde77f4ea3d";

export const LocationAttributeType = {
    DIRECT_CLIENT,
    LOCATION_PROGRAMS,
    LOCATION_CODE,
};